# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pratham/Projects/Networking

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pratham/Projects/Networking

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pratham/Projects/Networking/CMakeFiles /home/pratham/Projects/Networking//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pratham/Projects/Networking/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

Examples/testSocket.o: Examples/testSocket.cpp.o
.PHONY : Examples/testSocket.o

# target to build an object file
Examples/testSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Examples/testSocket.cpp.o
.PHONY : Examples/testSocket.cpp.o

Examples/testSocket.i: Examples/testSocket.cpp.i
.PHONY : Examples/testSocket.i

# target to preprocess a source file
Examples/testSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Examples/testSocket.cpp.i
.PHONY : Examples/testSocket.cpp.i

Examples/testSocket.s: Examples/testSocket.cpp.s
.PHONY : Examples/testSocket.s

# target to generate assembly for a file
Examples/testSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Examples/testSocket.cpp.s
.PHONY : Examples/testSocket.cpp.s

Server/http_server.o: Server/http_server.cpp.o
.PHONY : Server/http_server.o

# target to build an object file
Server/http_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Server/http_server.cpp.o
.PHONY : Server/http_server.cpp.o

Server/http_server.i: Server/http_server.cpp.i
.PHONY : Server/http_server.i

# target to preprocess a source file
Server/http_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Server/http_server.cpp.i
.PHONY : Server/http_server.cpp.i

Server/http_server.s: Server/http_server.cpp.s
.PHONY : Server/http_server.s

# target to generate assembly for a file
Server/http_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Server/http_server.cpp.s
.PHONY : Server/http_server.cpp.s

Server/web_socket.o: Server/web_socket.cpp.o
.PHONY : Server/web_socket.o

# target to build an object file
Server/web_socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Server/web_socket.cpp.o
.PHONY : Server/web_socket.cpp.o

Server/web_socket.i: Server/web_socket.cpp.i
.PHONY : Server/web_socket.i

# target to preprocess a source file
Server/web_socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Server/web_socket.cpp.i
.PHONY : Server/web_socket.cpp.i

Server/web_socket.s: Server/web_socket.cpp.s
.PHONY : Server/web_socket.s

# target to generate assembly for a file
Server/web_socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Server/web_socket.cpp.s
.PHONY : Server/web_socket.cpp.s

Socket/socket.o: Socket/socket.cpp.o
.PHONY : Socket/socket.o

# target to build an object file
Socket/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Socket/socket.cpp.o
.PHONY : Socket/socket.cpp.o

Socket/socket.i: Socket/socket.cpp.i
.PHONY : Socket/socket.i

# target to preprocess a source file
Socket/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Socket/socket.cpp.i
.PHONY : Socket/socket.cpp.i

Socket/socket.s: Socket/socket.cpp.s
.PHONY : Socket/socket.s

# target to generate assembly for a file
Socket/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Socket/socket.cpp.s
.PHONY : Socket/socket.cpp.s

Socket/socket_base.o: Socket/socket_base.cpp.o
.PHONY : Socket/socket_base.o

# target to build an object file
Socket/socket_base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Socket/socket_base.cpp.o
.PHONY : Socket/socket_base.cpp.o

Socket/socket_base.i: Socket/socket_base.cpp.i
.PHONY : Socket/socket_base.i

# target to preprocess a source file
Socket/socket_base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Socket/socket_base.cpp.i
.PHONY : Socket/socket_base.cpp.i

Socket/socket_base.s: Socket/socket_base.cpp.s
.PHONY : Socket/socket_base.s

# target to generate assembly for a file
Socket/socket_base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/Socket/socket_base.cpp.s
.PHONY : Socket/socket_base.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... example"
	@echo "... Examples/testSocket.o"
	@echo "... Examples/testSocket.i"
	@echo "... Examples/testSocket.s"
	@echo "... Server/http_server.o"
	@echo "... Server/http_server.i"
	@echo "... Server/http_server.s"
	@echo "... Server/web_socket.o"
	@echo "... Server/web_socket.i"
	@echo "... Server/web_socket.s"
	@echo "... Socket/socket.o"
	@echo "... Socket/socket.i"
	@echo "... Socket/socket.s"
	@echo "... Socket/socket_base.o"
	@echo "... Socket/socket_base.i"
	@echo "... Socket/socket_base.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

